#!/usr/bin/env ruby

require 'open-uri'
require 'cgi'
require 'csv'
require 'logger'
require 'nokogiri'
require 'watir-webdriver'

def logger
  @logger ||= Logger.new("log/京东_#{ARGV[0]}_图片.log")
end

def browser
  Selenium::WebDriver::Chrome.path = ENV['CHROME_PATH']
  @browser ||= Watir::Browser.new(:chrome)
end

begin
  logger.info "正在打开浏览器"

  Dir['./jd/*.csv'].each do |file|
    file_name = File.basename(file, '.csv')

    list = CSV.read(file).each do |csv_array|
      sku = csv_array[0]
      picture_url = csv_array[3]
      name = csv_array[1]

      picture_csv = "./jd/#{file_name}/#{sku}/pictures.csv"

      if test 's', picture_csv
        puts "跳过 #{name} !"
        next
      end

      begin
        logger.info "创建 #{picture_csv}"
        csv = CSV.open(picture_csv, "wb")
        browser.reset!
        logger.info "打开 #{picture_url}"
        browser.goto picture_url

        browser.ul(class: 'list-h').lis.each.with_index do |li, i|
          li.click
          logger.info "导入第 #{i+1} 张图片 URL."
          csv << [sku, browser.div(id: 'biger').img.src]
        end
      ensure
        logger.info '正在关闭 csv 文件.'
        csv.close
      end
    end
  end
ensure
  logger.info '正在关闭浏览器'
  browser.close unless @browser.nil?
end
