#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

Encoding::default_internal = 'utf-8'

def capture
  Dir["./#{site}/*.csv"].each do |file|
    self.keyword = File.basename(file, '.csv')

    logger.info "正在打开 #{keyword} 详细页面."

    list = CSV.read(file).each do |csv_array|
      sku = csv_array[0]
      name = csv_array[1]
      detail_url = csv_array[2]

      json_filename = "./#{site}/#{keyword}/#{sku}/details.json"

      if test 's', json_filename
        puts "跳过 #{name} 详细页面抓取 !"
        next
      end

      begin
        logger.info "创建 #{json_filename}"
        json_file = File.open(json_filename, "wb")
        content = Nokogiri::HTML.parse(open(detail_url).read)
        logger.info "正在抓取 #{name} 细节信息."
        details = content.css('div#product-detail-1 ul.detail-list li')
        details_hash = Hash[details.map {|e| e.text.split('：') }].to_json rescue "{}"
        specs = content.css('div#product-detail-2 table.Ptable tr')
        specs_hash = Hash[specification[2..-1].map {|e| [e.children[0].text, e.children[1].text] }].to_json rescue "{}"
        json_file.puts "{\"#{sku}\": {\"details\": #{details_hash}, \"specification\": #{specs_hash}}}"
        # 重构为一个方法
        logger.info "已抓取 #{name} 详细信息."
        puts "已抓取 #{name} 详细信息."
      ensure
        logger.info '正在关闭 json 文件.'
        json_file.close
      end
    end
  end
end

unless ARGV.empty?
  puts "无需提供参数, 请先使用 \033[0;33m./get_jd_list #{ARGV.join(' ')}\033[0m 生成抓取列表."
  exit 1
end

require_relative 'common'
include Common
capture
