#!/usr/bin/env ruby

require 'open-uri'
require 'cgi'
require 'csv'
require 'logger'
require 'nokogiri'
require 'watir-webdriver'

def logger
  @logger ||= Logger.new("logs/京东_#{ARGV[0]}_图片.log")
end

def browser
  logger.info "正在打开浏览器"
  Selenium::WebDriver::Chrome.path = ENV['CHROME_PATH']
  @browser ||= Watir::Browser.new(:chrome)
end

if ARGV[0].nil?
  puts '没有指定分类关键字'
  exit 1
end

list = CSV.read("jd/#{ARGV[0]}_列表.csv")[0]
sku = list[0]
picture_url = list[3]
name = list[1]

csv_filename = "./jd/#{ARGV[0]}/#{sku}/pictures.csv"

if test 's', csv_filename
  puts "跳过 #{name} !"
  exit
end

begin
  csv_file = CSV.open(csv_filename, "wb")
  browser.goto picture_url
  browser.ul(class: 'list-h').lis.each do |li|
    li.click
    csv_file << [sku, browser.div(id: 'biger').img.src]
  end
ensure
  logger.info '正在关闭浏览器'
  browser.close unless @browser.nil?
  logger.info '正在关闭 csv 文件.'
  csv_file.close unless csv_file.nil?
end
