#!/bin/sh

SCRIPT_DIRECTORY=$(dirname `which $0`)

$SCRIPT_DIRECTORY/get_jd_product_list
$SCRIPT_DIRECTORY/get_jd_product_detail
$SCRIPT_DIRECTORY/get_jd_picture_list
$SCRIPT_DIRECTORY/get_jd_picture_downloader
